name: Build GeckoView APK

on:
  workflow_dispatch: # permite ejecutar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configurar Gradle
        uses: gradle/gradle-build-action@v3

      - name: Compilar APK
        run: ./gradlew assembleRelease

      - name: Subir artefacto APK
        uses: actions/upload-artifact@v4
        with:
          name: geckoview-apk
          path: app/build/outputs/apk/release/app-release.apk
