name: Build GeckoView APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      - name: Actualizar Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 8.7 --distribution-type all

      - name: Compilar APK
        run: ./gradlew assembleRelease

      - name: Subir artefacto APK
        uses: actions/upload-artifact@v4
        with:
          name: geckoview-apk
          path: app/build/outputs/apk/release/app-release.apk
