name: Build GeckoView APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Paso 1: JDK 11 para instalar sdkmanager
      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Instalar Android SDK Command-line Tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/tools/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Instalar SDK Tools, NDK y CMake
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-29" "build-tools;29.0.3" \
                     "ndk;21.4.7075529" "cmake;3.10.2.4988404"

      # Paso 2: Cambiar a JDK 8 para Gradle 5.4.1
      - name: Configurar JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      - name: Compilar APK
        run: ./gradlew assembleRelease

      - name: Listar APKs generados
        run: ls -R app/build/outputs/apk/release/

      # Paso 3: Firmar con debug keystore
      - name: Firmar APK con debug keystore
        run: |
          # Crear debug keystore si no existe
          if [ ! -f ~/.android/debug.keystore ]; then
            mkdir -p ~/.android
            keytool -genkey -v -keystore ~/.android/debug.keystore \
              -alias androiddebugkey -storepass android -keypass android \
              -keyalg RSA -keysize 2048 -validity 10000 \
              -dname "CN=Android Debug,O=Android,C=US"
          fi

          # Buscar el APK generado (unsigned)
          APK_PATH=$(ls app/build/outputs/apk/release/*-unsigned.apk | head -n 1)
          echo "APK detectado: $APK_PATH"

          # Firmar el APK
          jarsigner -verbose -keystore ~/.android/debug.keystore \
            -storepass android -keypass android \
            "$APK_PATH" androiddebugkey

          # Alinear el APK para instalación
          zipalign -f 4 "$APK_PATH" app-release-signed.apk

      - name: Subir artefacto APK firmado
        uses: actions/upload-artifact@v4
        with:
          name: geckoview-apk-signed
          path: app-release-signed.apk
